version: '3.8'

services:
  luigi-app:
    build: .
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/luigi_production
      REDIS_URL: redis://redis:6379/0
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: production_password
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ACTION_CABLE_URL: wss://your-domain.com/cable
      ALLOWED_ORIGINS: your-domain.com
    depends_on:
      - postgres
      - redis  
      - neo4j
    ports:
      - "3333:3000"
    volumes:
      - ./storage:/rails/storage
      - ./log:/rails/log
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: luigi_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/production_password
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_default__database: luigi_knowledge
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/luigi_production
      REDIS_URL: redis://redis:6379/0
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: production_password
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
      - neo4j
    volumes:
      - ./storage:/rails/storage
      - ./log:/rails/log
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/nginx/ssl
    depends_on:
      - luigi-app
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  neo4j_logs: